-- begin SIGNALBOX_SIGNAL
alter table SIGNALBOX_SIGNAL add constraint FK_SIGNALBOX_SIGNAL_ON_GENERATOR foreign key (GENERATOR_ID) references SIGNALBOX_GENERATOR(ID)^
create index IDX_SIGNALBOX_SIGNAL_ON_GENERATOR on SIGNALBOX_SIGNAL (GENERATOR_ID)^
-- end SIGNALBOX_SIGNAL
